### ISSUE TITLE
When a role is added or removed from an user, Role don't work

### ISSUE THREAD

**Issue by amanzanotejon** [idealista/clickhouse_role#29]
### Description

If un user exists then when you modify any params for example roles params, the task is skipped, so roles aren't modified.

### Steps to Reproduce

1. Run molecule
2. Modify any user, for example adding a role to user
3. Check this user didn't get grant of role

**Expected behavior:**
I would expected user is modified if any params in the user var is modified

**Actual behavior:**
Once user is created this user can't be modified

**Reproduces how often:** 
Always

### Environment

- 0.3.2 and before

**Comment by ultraheroe** [comment]
Wont fix because this is a known side effect and we don't recommend to use the role management feature of the role for production environments, instead is recommended to manage the database within a playbook and doing query or external management.
